components_manager:
    task_processors:
        main-task-processor:
            worker_threads: 4
 
        fs-task-processor:
            worker_threads: 1
    components:
        server:
            listener:
                port: 8080

        default-server-middleware-pipeline-builder:
            append:
              - cors-middleware
        cors-middleware: 
            allowed-origins: 
                - http://localhost:5173
            allowed-methods: 
                - GET
                - PUT
            allow-credentials: true
        # cors-middleware-service: {} 

        # default-server-middleware-pipeline-builder:
        #         append: 
        #             - cors-middleware
        #             # - cors-middleware-service

        logging:
            loggers:
                default:
                    file_path: '@stderr'
                    level: error
                    overflow_behavior: discard

        administration-service:
            path: /api/v1/admin/{target}
            method: PUT
            auth:
                types:
                  - bearer
                scopes:
                  - admin


        worktime-service:
            path: /api/v1/user/time/{action}
            method: PUT
            auth:
                types:
                  - bearer
                scopes:
                  - user

        auth-service:
            path: /api/v1/user/auth/{action}
            method: GET,OPTIONS

        testsuite-support:

        db:
            # "postgresql://[user]:[password]@[host]:[port]/[database]"
            dbconnection: "postgresql://admin:admin@127.0.0.1:5432/company"
            blocking_task_processor: fs-task-processor
            dns_resolver: async
        
        auth-cache:
            pgcomponent: db
            update-interval: 10s
            chunk-size: 0

        dns-client:
            fs-task-processor: fs-task-processor