components_manager:
    task_processors:
        main-task-processor:
            worker_threads: 4
 
        fs-task-processor:
            worker_threads: 1
 
    components:
        server:
            listener:
                port: 8080
        logging:
            loggers:
                default:
                    file_path: '@stderr'
                    level: debug
                    overflow_behavior: discard
 
        administration-service:
            path: /api/v1/control
            method: PUT

        worktime-service:
            path: /api/v1/time
            method: GET,POST,PUT
        
        testsuite-support:

        db:
            # "postgresql://[user]:[password]@[host]:[port]/[database]"
            dbconnection: "postgresql://admin:admin@127.0.0.1:5432/company"
            dns_resolver: async

        dns-client:
            fs-task-processor: fs-task-processor